### ISSUE TITLE
Icons/glyphs apear to be broken

### ISSUE THREAD

**Issue by seanieb** [joonas-fi/emergency-details-printout#4]
<img width="347" alt="Screenshot 2024-03-07 at 1 16 09 AM" src="https://github.com/joonas-fi/emergency-details-printout/assets/191516/7eb7bbe2-9f9e-4110-926c-94433ce6ddb7">

The icons/glyphs aren't rendering. 

Tested using the latest versions of Firefox and Safari on MacOS.

**Comment by joonas-fi** [comment]
Thanks for reporting!

I can confirm this is the case.

Don't know what happened. Maybe this has broken over time (it's using quite an old browser engine for rendering, wkhtmltopdf):

https://github.com/joonas-fi/emergency-details-printout/blob/06258632f2fe2029eba7955e6ed762b28407148c/cmd/emergency-details-printout/templates/printout.html#L28-L32

or then #3 caused a regression. But I think I would have noticed it.

**Comment by joonas-fi** [comment]
Emojis broke due to twemoji broke due to MaxCDN shut down:

![image](https://github.com/joonas-fi/emergency-details-printout/assets/630151/b47a6a4f-1247-4260-b735-f55169524989)

[source](https://github.com/twitter/twemoji)

Curiously, the above quoted twemoji maxcdn URL works in my browser (redirects to `https://cdn.jsdelivr.net/...`) but it seems to have broke only in wkhtmltopdf context. Maybe jsdelivr blocks too old and insecure TLS versions which I guess comes due to wkhtmltopdf being so old. Just a guess, not worth investigating abandoned project..

Referencing twemoji from unpkg.com seems to fix this, not sure if the fix is a more relaxed server's TLS config in unpkg vs jsdelivr or if bumping twemoji to latest version fixed it (I would guess not since wkhtmltopdf has stayed the same so why pinned-to-specific-version JS lib would break over time..).

This is a quick fix, longer-term fix is: #5

**Comment by joonas-fi** [comment]
Fixed and new version deployed to the website, can you try again?

Thanks for the great actionable problem report! :hugs:

**Comment by seanieb** [comment]
Confirming it's Fixed! Thank you!
